export const copy = {
  es: {
    skip: 'Saltar al contenido',
    /** The examples' amounts, written as the app writes them. */
    money: {
      balance: ['1.280', ',00'],
      growing: '420,00',
      charge: '18,00',
      available: '1.000,00',
      moving: '280',
    },
    nav: {
      aria: 'Navegación principal',
      home: 'GatoPago — inicio',
      cycle: 'Cómo funciona',
      account: 'La cuenta',
      grow: 'Crecer',
      card: 'Card',
      developers: 'Developers',
      open: 'Abrir GatoPago',
      menuOpen: 'Abrir menú',
      menuClose: 'Cerrar menú',
      language: 'Cambiar a inglés',
      control: 'Tu control',
    },
    hero: {
      eyebrow: 'GatoPago · dólares en movimiento',
      titleLead: 'Tus dólares ya saben',
      titleAccent: 'moverse.',
      copy: 'Recibe, envía y paga en dólares digitales desde una cuenta que solo tú controlas. Sin frases semilla y sin comisiones de red.',
      primary: 'Abrir GatoPago',
      secondary: 'Ver cómo funciona',
      alpha: 'Beta pública',
      network: 'Arbitrum · Avalanche · Monad',
      funds: 'Con fondos de prueba',
      nap: 'Modo siesta',
      napOn: 'Modo siesta activado',
      napOff: 'Seguimos la pista de tu dinero',
      visualLabel: 'Gato pixelado de GatoPago',
      visualNote: 'Tu cuenta se mueve cuando tú das la señal.',
      packet: 'Pago en camino',
    },
    signals: [
      ['Tú tienes el control', 'Solo tus llaves pueden mover tu dinero.'],
      ['Sin frases semilla', 'Entras con la huella o el rostro de tu teléfono.'],
      ['Sin comisiones de red', 'GatoPago paga el gas por ti.'],
      ['Una cuenta, varias redes', 'La misma dirección en Arbitrum, Avalanche y Monad.'],
    ],
    cycle: {
      kicker: 'El recorrido de un pago',
      title: 'Así se mueve tu dinero.',
      accent: 'Sin jerga, paso a paso.',
      intro: 'Toca cada paso para ver qué pasa con tu dinero.',
      demo: 'Explorador interactivo',
      states: [
        {
          id: 'receive',
          number: '01',
          label: 'Recibir',
          short: 'Alguien te paga a tu @usuario o con tu link de cobro.',
          detail:
            'El pago llega directo a tu cuenta. Ves cuánto llegó y de quién, sin pasos extra.',
          status: 'Pago recibido',
        },
        {
          id: 'available',
          number: '02',
          label: 'Disponible',
          short: 'Listo para enviar o pagar.',
          detail:
            'Tu saldo está listo para usarse. No necesitas saber de contratos ni de redes para moverlo.',
          status: 'Saldo listo',
        },
        {
          id: 'growing',
          number: '03',
          label: 'Creciendo',
          short: 'Una parte gana intereses en Aave.',
          detail:
            'Eliges cuánto mover y ves la tasa antes de confirmar. Lo retiras cuando quieras.',
          status: 'Ganando intereses',
        },
        {
          id: 'use',
          number: '04',
          label: 'Usar',
          short: 'Envía, paga o cambia.',
          detail:
            'El dinero se mueve cuando tú decides. GatoPago prepara el camino; tu llave lo confirma.',
          status: 'Tú decides el siguiente paso',
        },
      ],
      label: 'Toca un paso',
    },
    account: {
      kicker: 'La cuenta',
      greeting: 'Hola, Dani',
      title: 'Una cuenta, no un tablero de blockchain.',
      copy: 'Créala en segundos con la huella o el rostro de tu teléfono y elige tu @usuario para recibir pagos.',
      concept: 'Así se ve tu cuenta',
      available: 'Disponible',
      growing: 'Creciendo',
      actions: ['Cobrar', 'Enviar', 'Cambiar', 'Escanear'],
      activity: 'Actividad reciente',
      received: 'Pago recibido',
      receivedFrom: 'de @cafe.norte',
      productNotes: [
        'Lo importante, primero',
        'Montos y estados que se entienden',
        'El detalle técnico, solo si lo buscas',
      ],
      action: 'Crear mi cuenta',
    },
    receive: {
      kicker: 'Cobrar',
      title: 'Cobra sin perseguir el pago.',
      copy: 'Comparte tu @usuario o crea un link con monto y concepto. Te pagan desde GatoPago o desde cualquier wallet.',
      linkLabel: 'Link de cobro',
      amountLabel: 'Total',
      item: '2 cafés + pan de queso',
      status: 'Por pagar',
      copyLink: 'Ver el cobro de ejemplo',
      note: 'Compártelo por WhatsApp, como QR o como link.',
      channels: ['WhatsApp', 'QR', 'Link', 'NFC · pronto'],
    },
    grow: {
      kicker: 'Crecer',
      titleLead: 'Una parte lista.',
      titleAccent: 'Otra, creciendo.',
      copy: 'Separa el dinero que vas a usar del que quieres poner a trabajar. Lo retiras cuando quieras.',
      available: 'Disponible',
      growing: 'Creciendo',
      amount: '280,00 USDC',
      route: 'Dónde crece',
      routeValue: 'Aave V3',
      rate: 'Tasa',
      rateValue: 'Variable',
      exit: 'Retiro',
      exitValue: 'Cuando quieras',
      risk: 'Antes de confirmar ves la tasa del día y sus condiciones. La tasa no está garantizada.',
    },
    control: {
      kicker: 'Control sin fricción',
      title: 'La experiencia es simple. El control es tuyo.',
      copy: 'Tu cuenta vive en la blockchain y responde solo a tus llaves. Ni siquiera GatoPago puede mover tu dinero.',
      items: [
        ['Passkey', 'Entras con la huella o el rostro. Cada envío te pide su propia confirmación.'],
        [
          'Llaves de respaldo',
          'Agrega otra llave en otro dispositivo o gestor y conserva siempre el acceso a tu cuenta.',
        ],
        [
          'Todo a la vista',
          'Destino, red y monto antes de confirmar, y el comprobante en la blockchain después.',
        ],
      ],
      demo: 'Probar la confirmación',
      demoHint: 'Así se ve una decisión importante en GatoPago.',
    },
    dialog: {
      eyebrow: 'Vista previa',
      title: 'Revisa antes de mover',
      amount: '18,00 USDC',
      rows: [
        ['Destino', '@cafe.norte'],
        ['Concepto', 'Desayuno'],
        ['Red', 'Arbitrum'],
        ['Comisión de red', 'Gratis'],
      ],
      disclaimer: 'Así revisas cada pago antes de confirmarlo.',
      cancel: 'Volver',
      confirm: 'Entendido',
      close: 'Cerrar diálogo',
    },
    card: {
      kicker: 'Lo que viene',
      title: 'Tu saldo, también en la tienda de la esquina.',
      copy: 'Estamos diseñando GatoPago Card para que pagues con tu mismo saldo en cualquier comercio.',
      badge: 'Próximamente',
      cardLabel: 'GATOPAGO · CARD',
      cardName: 'DANI',
      waitlist: 'Anotarme desde la app',
      notice: 'Cuéntanos cómo la usarías y te avisamos primero.',
    },
    developers: {
      kicker: 'GatoPago para Developers',
      title: 'Dale más vidas a tus pagos.',
      copy: 'Payment intents, checkout, sandbox y webhooks firmados para cobrar en USDC sin construir una wallet desde cero.',
      features: ['Payment intents', 'Idempotencia', 'Webhooks firmados', 'Sandbox de prueba'],
      docs: 'Ver la documentación',
      pilot: 'Abrir la consola',
      response: 'intent creada',
      note: 'Crea tu API key en la consola y haz tu primer cobro de prueba en minutos.',
    },
    faq: {
      kicker: 'Preguntas frecuentes',
      title: 'Lo que suelen preguntarnos.',
      items: [
        [
          '¿Qué es GatoPago?',
          'Una cuenta de dólares digitales (USDC) que controlas con la passkey de tu teléfono. Sin frases semilla y sin comisiones de red.',
        ],
        [
          '¿Puedo usar dinero real?',
          'Todavía no. GatoPago está en beta pública sobre redes de prueba (Arbitrum Sepolia, Avalanche Fuji y Monad testnet). Úsala con fondos de prueba.',
        ],
        [
          '¿Quién controla mi dinero?',
          'Solo tú. Tu cuenta vive en la blockchain y cada movimiento lo confirma tu llave. GatoPago no puede mover tus fondos.',
        ],
        [
          '¿Qué pasa si cambio de teléfono?',
          'Tu passkey se sincroniza con tu gestor de contraseñas, así que entras igual desde el nuevo. Para más tranquilidad, agrega una llave de respaldo en Seguridad.',
        ],
        [
          '¿Quién paga el gas?',
          'GatoPago. Crear tu cuenta y enviar dinero no te cuesta comisiones de red.',
        ],
      ],
    },
    final: {
      eyebrow: 'Tu dinero, con siete vidas',
      title: 'Haz que cada pago caiga de pie.',
      copy: 'Crea tu cuenta en segundos y descubre lo fácil que es mover dólares digitales.',
      primary: 'Abrir GatoPago',
      secondary: 'Volver al recorrido',
    },
    footer: {
      line: 'Tus dólares ya saben moverse. Tu cuenta sigue bajo tu control.',
      product: 'Producto',
      company: 'GatoPago',
      legal: 'Legal',
      links: ['Cómo funciona', 'La cuenta', 'Crecer', 'Developers'],
      terms: 'Términos',
      privacy: 'Privacidad',
      status: 'Beta pública · redes de prueba',
      rights: 'GatoPago. Hecho con cuidado en Bolivia.',
    },
  },
  en: {
    skip: 'Skip to content',
    money: {
      balance: ['1,280', '.00'],
      growing: '420.00',
      charge: '18.00',
      available: '1,000.00',
      moving: '280',
    },
    nav: {
      aria: 'Main navigation',
      home: 'GatoPago — home',
      cycle: 'How it works',
      account: 'The account',
      grow: 'Grow',
      card: 'Card',
      developers: 'Developers',
      open: 'Open GatoPago',
      menuOpen: 'Open menu',
      menuClose: 'Close menu',
      language: 'Cambiar a español',
      control: 'Your control',
    },
    hero: {
      eyebrow: 'GatoPago · dollars in motion',
      titleLead: 'Your dollars already',
      titleAccent: 'know how to move.',
      copy: 'Receive, send, and pay in digital dollars from an account only you control. No seed phrases and no network fees.',
      primary: 'Open GatoPago',
      secondary: 'See how it works',
      alpha: 'Public beta',
      network: 'Arbitrum · Avalanche · Monad',
      funds: 'With test funds',
      nap: 'Nap mode',
      napOn: 'Nap mode is on',
      napOff: 'We are tracking your money',
      visualLabel: 'GatoPago pixel cat',
      visualNote: 'Your account moves when you give the signal.',
      packet: 'Payment on the move',
    },
    signals: [
      ['You are in control', 'Only your keys can move your money.'],
      ['No seed phrases', 'Sign in with your phone’s fingerprint or face.'],
      ['No network fees', 'GatoPago pays the gas for you.'],
      ['One account, many networks', 'The same address on Arbitrum, Avalanche and Monad.'],
    ],
    cycle: {
      kicker: 'A payment’s journey',
      title: 'This is how your money moves.',
      accent: 'No jargon, step by step.',
      intro: 'Tap each step to see what happens to your money.',
      demo: 'Interactive explorer',
      states: [
        {
          id: 'receive',
          number: '01',
          label: 'Receive',
          short: 'Someone pays your @username or your payment link.',
          detail:
            'The payment lands straight in your account. You see how much arrived and from whom, with no extra steps.',
          status: 'Payment received',
        },
        {
          id: 'available',
          number: '02',
          label: 'Available',
          short: 'Ready to send or pay.',
          detail:
            'Your balance is ready to use. You do not need to know about contracts or networks to move it.',
          status: 'Balance ready',
        },
        {
          id: 'growing',
          number: '03',
          label: 'Growing',
          short: 'Part of it earns interest on Aave.',
          detail:
            'You choose how much to move and see the rate before confirming. Withdraw it whenever you want.',
          status: 'Earning interest',
        },
        {
          id: 'use',
          number: '04',
          label: 'Use',
          short: 'Send, pay, or swap.',
          detail: 'Money moves when you decide. GatoPago prepares the path; your key confirms it.',
          status: 'You choose the next step',
        },
      ],
      label: 'Tap a step',
    },
    account: {
      kicker: 'The account',
      greeting: 'Hi, Dani',
      title: 'An account, not a blockchain dashboard.',
      copy: 'Create it in seconds with your phone’s fingerprint or face, and pick your @username to get paid.',
      concept: 'What your account looks like',
      available: 'Available',
      growing: 'Growing',
      actions: ['Request', 'Send', 'Swap', 'Scan'],
      activity: 'Recent activity',
      received: 'Payment received',
      receivedFrom: 'from @cafe.norte',
      productNotes: [
        'What matters comes first',
        'Amounts and states that make sense',
        'Technical detail, only if you look for it',
      ],
      action: 'Create my account',
    },
    receive: {
      kicker: 'Get paid',
      title: 'Get paid without chasing the payment.',
      copy: 'Share your @username or create a link with an amount and a note. People pay from GatoPago or from any wallet.',
      linkLabel: 'Payment link',
      amountLabel: 'Total',
      item: '2 coffees + cheese bread',
      status: 'Awaiting payment',
      copyLink: 'See the example request',
      note: 'Share it on WhatsApp, as a QR code or as a link.',
      channels: ['WhatsApp', 'QR', 'Link', 'NFC · soon'],
    },
    grow: {
      kicker: 'Grow',
      titleLead: 'One part ready.',
      titleAccent: 'Another, growing.',
      copy: 'Separate the money you will use from the money you want to put to work. Withdraw it whenever you want.',
      available: 'Available',
      growing: 'Growing',
      amount: '280.00 USDC',
      route: 'Where it grows',
      routeValue: 'Aave V3',
      rate: 'Rate',
      rateValue: 'Variable',
      exit: 'Withdrawal',
      exitValue: 'Whenever you want',
      risk: 'Before confirming you see today’s rate and its terms. The rate is not guaranteed.',
    },
    control: {
      kicker: 'Control without friction',
      title: 'The experience is simple. The control is yours.',
      copy: 'Your account lives on the blockchain and answers only to your keys. Not even GatoPago can move your money.',
      items: [
        [
          'Passkey',
          'Sign in with your fingerprint or face. Every transfer asks for its own confirmation.',
        ],
        [
          'Backup keys',
          'Add another key on another device or password manager and always keep access to your account.',
        ],
        [
          'Everything in sight',
          'Destination, network and amount before you confirm, and the receipt on the blockchain after.',
        ],
      ],
      demo: 'Try the confirmation',
      demoHint: 'This is how an important decision looks in GatoPago.',
    },
    dialog: {
      eyebrow: 'Preview',
      title: 'Review before moving',
      amount: '18.00 USDC',
      rows: [
        ['Destination', '@cafe.norte'],
        ['Note', 'Breakfast'],
        ['Network', 'Arbitrum'],
        ['Network fee', 'Free'],
      ],
      disclaimer: 'This is how you review every payment before confirming it.',
      cancel: 'Go back',
      confirm: 'Got it',
      close: 'Close dialog',
    },
    card: {
      kicker: 'What is next',
      title: 'Your balance, at the corner store too.',
      copy: 'We are designing GatoPago Card so you can pay with your same balance at any store.',
      badge: 'Coming soon',
      cardLabel: 'GATOPAGO · CARD',
      cardName: 'DANI',
      waitlist: 'Sign up from the app',
      notice: 'Tell us how you would use it and we will let you know first.',
    },
    developers: {
      kicker: 'GatoPago for Developers',
      title: 'Give your payments more lives.',
      copy: 'Payment intents, checkout, sandbox, and signed webhooks to get paid in USDC without building a wallet from scratch.',
      features: ['Payment intents', 'Idempotency', 'Signed webhooks', 'Test sandbox'],
      docs: 'Read the documentation',
      pilot: 'Open the console',
      response: 'intent created',
      note: 'Create your API key in the console and make your first test charge in minutes.',
    },
    faq: {
      kicker: 'Frequently asked questions',
      title: 'What people usually ask us.',
      items: [
        [
          'What is GatoPago?',
          'A digital-dollar (USDC) account you control with your phone’s passkey. No seed phrases and no network fees.',
        ],
        [
          'Can I use real money?',
          'Not yet. GatoPago is in public beta on test networks (Arbitrum Sepolia, Avalanche Fuji and Monad testnet). Use it with test funds.',
        ],
        [
          'Who controls my money?',
          'Only you. Your account lives on the blockchain and every movement is confirmed by your key. GatoPago cannot move your funds.',
        ],
        [
          'What if I change phones?',
          'Your passkey syncs with your password manager, so you sign in the same way on the new one. For extra peace of mind, add a backup key in Security.',
        ],
        [
          'Who pays for gas?',
          'GatoPago. Creating your account and sending money cost you no network fees.',
        ],
      ],
    },
    final: {
      eyebrow: 'Your money, with nine lives',
      title: 'Make every payment land on its feet.',
      copy: 'Create your account in seconds and see how easy moving digital dollars can be.',
      primary: 'Open GatoPago',
      secondary: 'Back to the journey',
    },
    footer: {
      line: 'Your dollars already know how to move. Your account stays under your control.',
      product: 'Product',
      company: 'GatoPago',
      legal: 'Legal',
      links: ['How it works', 'The account', 'Grow', 'Developers'],
      terms: 'Terms',
      privacy: 'Privacy',
      status: 'Public beta · test networks',
      rights: 'GatoPago. Made with care in Bolivia.',
    },
  },
} as const;
