export const copy = {
  es: {
    skip: 'Saltar al contenido',
    nav: {
      aria: 'Navegación principal',
      home: 'GatoPago — inicio',
      cycle: 'El ciclo',
      account: 'La cuenta',
      grow: 'Crecer',
      card: 'Card',
      developers: 'Developers',
      open: 'Abrir GatoPago',
      menuOpen: 'Abrir menú',
      menuClose: 'Cerrar menú',
      language: 'Cambiar a inglés',
      control: 'Tu control',
    },
    hero: {
      eyebrow: 'GatoPago · dólares en movimiento',
      titleLead: 'Tus dólares ya saben',
      titleAccent: 'moverse.',
      copy: 'Recibe, envía y paga dólares digitales desde una cuenta que solo tú controlas. Sin frases semilla y sin comisiones de red.',
      primary: 'Abrir GatoPago',
      secondary: 'Ver cómo funciona',
      alpha: 'Beta pública',
      network: 'Arbitrum · Avalanche · Monad',
      funds: 'Con fondos de prueba',
      nap: 'Modo siesta',
      napOn: 'Modo siesta activado',
      napOff: 'Seguimos la pista de tu dinero',
      visualLabel: 'Gato pixelado de GatoPago',
      visualNote: 'Tu cuenta se mueve cuando tú das la señal.',
      packet: 'Pago en camino',
    },
    signals: [
      ['Tú tienes el control', 'Solo tus llaves pueden mover tu dinero.'],
      ['Sin frases semilla', 'Entras con la huella o el rostro de tu teléfono.'],
      ['Sin comisiones de red', 'GatoPago paga el gas por ti.'],
      ['Una cuenta, varias redes', 'La misma dirección en Arbitrum, Avalanche y Monad.'],
    ],
    cycle: {
      kicker: 'El recorrido de un pago',
      title: 'Tu dinero no vive en una lista de tokens.',
      accent: 'Vive en estados que entiendes.',
      intro: 'Así se mueve tu dinero en GatoPago, paso a paso.',
      demo: 'Explorador interactivo',
      states: [
        {
          id: 'receive',
          number: '01',
          label: 'Recibir',
          short: 'Alguien te paga a tu @usuario o a tu dirección.',
          detail:
            'El pago llega directo a tu cuenta. Ves cuánto llegó y en qué red, sin pasos extra.',
          status: 'Pago recibido',
        },
        {
          id: 'available',
          number: '02',
          label: 'Disponible',
          short: 'Listo para enviar o pagar.',
          detail:
            'Tu saldo está listo para usarse. No necesitas saber de contratos ni de redes para moverlo.',
          status: 'Saldo listo',
        },
        {
          id: 'growing',
          number: '03',
          label: 'Creciendo',
          short: 'Pronto: pon una parte a trabajar en Aave V3.',
          detail:
            'Tú decidirás cuánto mover y verás la tasa, el protocolo y cómo retirar antes de confirmar.',
          status: 'Próximamente',
        },
        {
          id: 'use',
          number: '04',
          label: 'Usar',
          short: 'Envía, paga o retira.',
          detail:
            'El dinero se mueve cuando tú decides. GatoPago prepara el camino; tu llave lo confirma.',
          status: 'Tú decides el siguiente paso',
        },
      ],
      label: 'GUÍA',
    },
    account: {
      kicker: 'La cuenta',
      greeting: 'Hola, Dani',
      title: 'Una cuenta, no un tablero de blockchain.',
      copy: 'Crea tu cuenta con una passkey en segundos y elige tu @usuario para recibir pagos.',
      concept: 'Así se ve tu cuenta',
      available: 'Disponible',
      growing: 'Creciendo',
      actions: ['Recibir', 'Enviar', 'Escanear', 'Crecer'],
      activity: 'Actividad reciente',
      received: 'Pago recibido',
      receivedFrom: 'de @cafe.norte',
      productNotes: [
        'Lo importante primero',
        'Montos y estados en lenguaje humano',
        'El detalle técnico, solo si lo buscas',
      ],
      action: 'Crear mi cuenta',
    },
    receive: {
      kicker: 'Cobrar',
      title: 'Cobra sin perseguir el pago.',
      copy: 'Comparte tu @usuario y recibe al instante. Muy pronto también podrás crear links y QR con monto y concepto.',
      linkLabel: 'Link de cobro',
      amountLabel: 'Total',
      item: '2 cafés + pan de queso',
      status: 'Próximamente',
      copyLink: 'Copiar ejemplo',
      copied: '¡Ejemplo copiado!',
      note: 'Así se verán tus links de cobro. Hoy ya puedes cobrar con tu @usuario.',
      channels: ['WhatsApp', 'QR', 'Mensaje', 'NFC · pronto'],
    },
    grow: {
      kicker: 'Crecer · Próximamente',
      titleLead: 'Una parte lista.',
      titleAccent: 'Otra, creciendo.',
      copy: 'Separa el dinero que usarás pronto del que quieres poner a trabajar, con la claridad de siempre.',
      available: 'Disponible',
      growing: 'Creciendo',
      amount: 'USDC 280.00',
      route: 'Ruta guiada',
      routeValue: 'GatoPago → Aave V3',
      rate: 'Tasa',
      rateValue: 'Variable',
      exit: 'Salida',
      exitValue: 'Cuando tú quieras',
      risk: 'Antes de confirmar verás la tasa, el protocolo y sus condiciones.',
      action: 'Ver cómo funciona',
    },
    move: {
      kicker: 'Usar',
      title: 'Mover dinero debería sentirse como elegir un camino.',
      copy: 'Verbos que ya conoces. Cada camino termina en una revisión clara antes de confirmar.',
      paths: [
        ['Recibir', 'Con tu @usuario o tu dirección.', 'R'],
        ['Enviar', 'A un @usuario o una dirección, sin comisión.', 'E'],
        ['Escanear', 'Apunta la cámara a un QR y listo.', 'Q'],
        ['Cambiar', 'Pronto: entre monedas digitales.', 'C'],
      ],
      preview: 'Siempre revisas antes de confirmar',
    },
    control: {
      kicker: 'Control sin fricción',
      title: 'La experiencia es simple. El control es tuyo.',
      copy: 'Tu cuenta vive en la blockchain y responde solo a tus llaves. Ni siquiera GatoPago puede mover tu dinero.',
      items: [
        ['Passkey', 'Entras con la huella o el rostro. Cada envío te pide su propia confirmación.'],
        [
          'Llaves de respaldo',
          'Agrega otra llave en otro dispositivo o gestor y conserva siempre el acceso a tu cuenta.',
        ],
        [
          'Todo a la vista',
          'Destino, red y monto antes de confirmar, y el comprobante en la blockchain después.',
        ],
      ],
      demo: 'Probar diálogo de confirmación',
      demoHint: 'Así se ve una decisión importante en GatoPago.',
    },
    dialog: {
      eyebrow: 'Vista previa',
      title: 'Revisa antes de mover',
      amount: '18.00 USDC',
      rows: [
        ['Destino', '@cafe.norte'],
        ['Concepto', 'Desayuno'],
        ['Red', 'Arbitrum'],
        ['Comisión de red', 'Gratis'],
      ],
      disclaimer: 'Así revisas cada pago antes de confirmarlo.',
      cancel: 'Volver',
      confirm: 'Entendido',
      close: 'Cerrar diálogo',
    },
    card: {
      kicker: 'Próximo camino',
      title: 'El siguiente paso conecta con el mundo cotidiano.',
      copy: 'Estamos diseñando GatoPago Card: tu mismo saldo, para pagar en cualquier comercio.',
      badge: 'Próximamente',
      cardLabel: 'GATOPAGO · CARD',
      cardName: 'DANI',
      waitlist: 'Preguntas frecuentes',
      notice: 'Llega en una próxima versión.',
    },
    developers: {
      kicker: 'GatoPago para Developers',
      title: 'Dale más vidas a tus pagos.',
      copy: 'Payment intents, checkout, sandbox y webhooks firmados para cobrar en USDC sin construir una wallet desde cero.',
      features: ['Payment intents', 'Idempotencia', 'Webhooks firmados', 'Sandbox de prueba'],
      docs: 'Explorar documentación',
      pilot: 'Conversar sobre un piloto',
      response: 'intent creada',
      note: 'Integra en minutos con la documentación y el sandbox.',
    },
    faq: {
      kicker: 'Preguntas frecuentes',
      title: 'Todo lo que necesitas saber.',
      items: [
        [
          '¿Qué es GatoPago?',
          'Una cuenta de dólares digitales (USDC) que controlas con la passkey de tu teléfono. Sin frases semilla y sin comisiones de red.',
        ],
        [
          '¿Puedo usar dinero real?',
          'Todavía no. GatoPago está en beta pública sobre redes de prueba (Arbitrum Sepolia, Avalanche Fuji y Monad testnet). Úsala con fondos de prueba.',
        ],
        [
          '¿Quién controla mi dinero?',
          'Solo tú. Tu cuenta vive en la blockchain y cada movimiento lo confirma tu llave. GatoPago no puede mover tus fondos.',
        ],
        [
          '¿Qué pasa si cambio de teléfono?',
          'Tu passkey se sincroniza con tu gestor de contraseñas, así que entras igual desde el nuevo. Para más tranquilidad, agrega una llave de respaldo en Seguridad.',
        ],
        [
          '¿Quién paga el gas?',
          'GatoPago. Crear tu cuenta y enviar dinero no te cuesta comisiones de red.',
        ],
      ],
    },
    final: {
      eyebrow: 'Tu dinero, con siete vidas',
      title: 'Haz que cada pago caiga de pie.',
      copy: 'Crea tu cuenta en segundos y descubre lo fácil que es mover dólares digitales.',
      primary: 'Abrir GatoPago',
      secondary: 'Volver al recorrido',
    },
    footer: {
      line: 'Tus dólares ya saben moverse. Tu cuenta sigue bajo tu control.',
      product: 'Producto',
      company: 'GatoPago',
      legal: 'Legal',
      links: ['El ciclo', 'La cuenta', 'Crecer', 'Developers'],
      terms: 'Términos',
      privacy: 'Privacidad',
      status: 'Beta pública · redes de prueba',
      rights: 'GatoPago. Construido con cuidado en Bolivia.',
    },
  },
  en: {
    skip: 'Skip to content',
    nav: {
      aria: 'Main navigation',
      home: 'GatoPago — home',
      cycle: 'The cycle',
      account: 'The account',
      grow: 'Grow',
      card: 'Card',
      developers: 'Developers',
      open: 'Open GatoPago',
      menuOpen: 'Open menu',
      menuClose: 'Close menu',
      language: 'Cambiar a español',
      control: 'Your control',
    },
    hero: {
      eyebrow: 'GatoPago · dollars in motion',
      titleLead: 'Your dollars already',
      titleAccent: 'know how to move.',
      copy: 'Receive, send, and pay digital dollars from an account only you control. No seed phrases and no network fees.',
      primary: 'Open GatoPago',
      secondary: 'See how it works',
      alpha: 'Public beta',
      network: 'Arbitrum · Avalanche · Monad',
      funds: 'With test funds',
      nap: 'Nap mode',
      napOn: 'Nap mode is on',
      napOff: 'We are tracking your money',
      visualLabel: 'GatoPago pixel cat',
      visualNote: 'Your account moves when you give the signal.',
      packet: 'Payment on the move',
    },
    signals: [
      ['You are in control', 'Only your keys can move your money.'],
      ['No seed phrases', 'Sign in with your phone’s fingerprint or face.'],
      ['No network fees', 'GatoPago pays the gas for you.'],
      ['One account, many networks', 'The same address on Arbitrum, Avalanche and Monad.'],
    ],
    cycle: {
      kicker: 'A payment’s journey',
      title: 'Your money does not live in a token list.',
      accent: 'It lives in states you understand.',
      intro: 'This is how your money moves in GatoPago, step by step.',
      demo: 'Interactive explorer',
      states: [
        {
          id: 'receive',
          number: '01',
          label: 'Receive',
          short: 'Someone pays your @username or your address.',
          detail:
            'The payment lands straight in your account. You see how much arrived and on which network, with no extra steps.',
          status: 'Payment received',
        },
        {
          id: 'available',
          number: '02',
          label: 'Available',
          short: 'Ready to send or pay.',
          detail:
            'Your balance is ready to use. You do not need to know about contracts or networks to move it.',
          status: 'Balance ready',
        },
        {
          id: 'growing',
          number: '03',
          label: 'Growing',
          short: 'Coming soon: put a part to work in Aave V3.',
          detail:
            'You will choose how much to move and see the rate, the protocol and how to withdraw before confirming.',
          status: 'Coming soon',
        },
        {
          id: 'use',
          number: '04',
          label: 'Use',
          short: 'Send, pay, or withdraw.',
          detail: 'Money moves when you decide. GatoPago prepares the path; your key confirms it.',
          status: 'You choose the next step',
        },
      ],
      label: 'GUIDE',
    },
    account: {
      kicker: 'The account',
      greeting: 'Hi, Dani',
      title: 'An account, not a blockchain dashboard.',
      copy: 'Create your account with a passkey in seconds and pick your @username to get paid.',
      concept: 'What your account looks like',
      available: 'Available',
      growing: 'Growing',
      actions: ['Receive', 'Send', 'Scan', 'Grow'],
      activity: 'Recent activity',
      received: 'Payment received',
      receivedFrom: 'from @cafe.norte',
      productNotes: [
        'What matters comes first',
        'Amounts and states in human language',
        'Technical detail, only if you look for it',
      ],
      action: 'Create my account',
    },
    receive: {
      kicker: 'Get paid',
      title: 'Get paid without chasing the payment.',
      copy: 'Share your @username and get paid instantly. Soon you will also create links and QR codes with an amount and a note.',
      linkLabel: 'Payment link',
      amountLabel: 'Total',
      item: '2 coffees + cheese bread',
      status: 'Coming soon',
      copyLink: 'Copy example',
      copied: 'Example copied!',
      note: 'This is how your payment links will look. You can already get paid with your @username.',
      channels: ['WhatsApp', 'QR', 'Message', 'NFC · soon'],
    },
    grow: {
      kicker: 'Grow · Coming soon',
      titleLead: 'One part ready.',
      titleAccent: 'Another, growing.',
      copy: 'Separate the money you will use soon from what you want to put to work, with the same clarity as always.',
      available: 'Available',
      growing: 'Growing',
      amount: 'USDC 280.00',
      route: 'Guided route',
      routeValue: 'GatoPago → Aave V3',
      rate: 'Rate',
      rateValue: 'Variable',
      exit: 'Exit',
      exitValue: 'Whenever you want',
      risk: 'Before confirming, you will see the rate, the protocol and its terms.',
      action: 'See how it works',
    },
    move: {
      kicker: 'Use',
      title: 'Moving money should feel like choosing a path.',
      copy: 'Verbs you already know. Every path ends in a clear review before you confirm.',
      paths: [
        ['Receive', 'With your @username or your address.', 'R'],
        ['Send', 'To a @username or an address, with no fees.', 'S'],
        ['Scan', 'Point the camera at a QR code and you are done.', 'Q'],
        ['Swap', 'Coming soon: between digital currencies.', 'W'],
      ],
      preview: 'You always review before confirming',
    },
    control: {
      kicker: 'Control without friction',
      title: 'The experience is simple. The control is yours.',
      copy: 'Your account lives on the blockchain and answers only to your keys. Not even GatoPago can move your money.',
      items: [
        [
          'Passkey',
          'Sign in with your fingerprint or face. Every transfer asks for its own confirmation.',
        ],
        [
          'Backup keys',
          'Add another key on another device or password manager and always keep access to your account.',
        ],
        [
          'Everything in sight',
          'Destination, network and amount before you confirm, and the receipt on the blockchain after.',
        ],
      ],
      demo: 'Try the confirmation dialog',
      demoHint: 'This is how an important decision looks in GatoPago.',
    },
    dialog: {
      eyebrow: 'Preview',
      title: 'Review before moving',
      amount: '18.00 USDC',
      rows: [
        ['Destination', '@cafe.norte'],
        ['Note', 'Breakfast'],
        ['Network', 'Arbitrum'],
        ['Network fee', 'Free'],
      ],
      disclaimer: 'This is how you review every payment before confirming it.',
      cancel: 'Go back',
      confirm: 'Got it',
      close: 'Close dialog',
    },
    card: {
      kicker: 'Next path',
      title: 'The next step connects to everyday life.',
      copy: 'We are designing GatoPago Card: your same balance, to pay at any store.',
      badge: 'Coming soon',
      cardLabel: 'GATOPAGO · CARD',
      cardName: 'DANI',
      waitlist: 'Frequently asked questions',
      notice: 'Arriving in a future release.',
    },
    developers: {
      kicker: 'GatoPago for Developers',
      title: 'Give your payments more lives.',
      copy: 'Payment intents, checkout, sandbox, and signed webhooks to get paid in USDC without building a wallet from scratch.',
      features: ['Payment intents', 'Idempotency', 'Signed webhooks', 'Test sandbox'],
      docs: 'Explore documentation',
      pilot: 'Talk about a pilot',
      response: 'intent created',
      note: 'Integrate in minutes with the documentation and the sandbox.',
    },
    faq: {
      kicker: 'Frequently asked questions',
      title: 'Everything you need to know.',
      items: [
        [
          'What is GatoPago?',
          'A digital-dollar (USDC) account you control with your phone’s passkey. No seed phrases and no network fees.',
        ],
        [
          'Can I use real money?',
          'Not yet. GatoPago is in public beta on test networks (Arbitrum Sepolia, Avalanche Fuji and Monad testnet). Use it with test funds.',
        ],
        [
          'Who controls my money?',
          'Only you. Your account lives on the blockchain and every movement is confirmed by your key. GatoPago cannot move your funds.',
        ],
        [
          'What if I change phones?',
          'Your passkey syncs with your password manager, so you sign in the same way on the new one. For extra peace of mind, add a backup key in Security.',
        ],
        [
          'Who pays for gas?',
          'GatoPago. Creating your account and sending money cost you no network fees.',
        ],
      ],
    },
    final: {
      eyebrow: 'Your money, with nine lives',
      title: 'Make every payment land on its feet.',
      copy: 'Create your account in seconds and see how easy moving digital dollars can be.',
      primary: 'Open GatoPago',
      secondary: 'Back to the journey',
    },
    footer: {
      line: 'Your dollars already know how to move. Your account stays under your control.',
      product: 'Product',
      company: 'GatoPago',
      legal: 'Legal',
      links: ['The cycle', 'The account', 'Grow', 'Developers'],
      terms: 'Terms',
      privacy: 'Privacy',
      status: 'Public beta · test networks',
      rights: 'GatoPago. Built with care in Bolivia.',
    },
  },
} as const;
