export const copy = {
  es: {
    skip: 'Saltar al contenido',
    nav: {
      aria: 'Navegación principal',
      home: 'GatoPago — inicio',
      cycle: 'El ciclo',
      account: 'La cuenta',
      grow: 'Crecer',
      card: 'Card',
      developers: 'Developers',
      open: 'Abrir GatoPago',
      menuOpen: 'Abrir menú',
      menuClose: 'Cerrar menú',
      language: 'Cambiar a inglés',
    },
    hero: {
      eyebrow: 'GatoPago · dólares en movimiento',
      titleLead: 'Tus dólares ya saben',
      titleAccent: 'moverse.',
      copy:
        'Cobra, paga, cambia y haz crecer dólares digitales desde una cuenta que tú controlas. GatoPago se ocupa del camino; tú decides cada movimiento.',
      primary: 'Ver estado de la App',
      secondary: 'Ver cómo funciona',
      alpha: 'Vista previa V3',
      network: 'Testnet · en desarrollo',
      funds: 'Fondos de prueba',
      nap: 'Modo siesta',
      napOn: 'Modo siesta activado',
      napOff: 'Seguimos la pista de tu dinero',
      visualLabel: 'Gato pixelado de GatoPago',
      visualNote: 'Tu cuenta se mueve cuando tú das la señal.',
      packet: 'Pago en camino',
    },
    signals: [
      ['Tú autorizas', 'Cada movimiento necesita una llave activa.'],
      ['Identidad y firma separadas', 'Google o correo para entrar; tus llaves para autorizar.'],
      ['Gas patrocinado', 'Previsto para las pruebas, sujeto a disponibilidad y límites.'],
      ['Riesgos visibles', 'Rutas, costos y condiciones antes de confirmar.'],
    ],
    cycle: {
      kicker: 'El recorrido de un pago',
      title: 'Tu dinero no vive en una lista de tokens.',
      accent: 'Vive en estados que entiendes.',
      intro:
        'Sigue el recorrido de un pago. Toca cada estado para ver qué cambia y qué permanece bajo tu control.',
      demo: 'Explorador interactivo',
      states: [
        {
          id: 'receive',
          number: '01',
          label: 'Recibir',
          short: 'Alguien paga tu link, QR o usuario.',
          detail:
            'El pago entra a tu cuenta onchain. Ves de dónde llegó, el monto y la red antes de hacer cualquier otra cosa.',
          status: 'Pago detectado',
        },
        {
          id: 'available',
          number: '02',
          label: 'Disponible',
          short: 'Listo para pagar, enviar o cambiar.',
          detail:
            'Disponible es la parte líquida de tu saldo. No necesitas aprender nombres de contratos para saber qué puedes usar ahora.',
          status: 'Saldo listo',
        },
        {
          id: 'growing',
          number: '03',
          label: 'Creciendo',
          short: 'Una parte puede entrar a Aave V3.',
          detail:
            'Tú eliges cuánto mover. La tasa es variable y la app debe mostrar riesgos, protocolo y salida antes de confirmar.',
          status: 'Ruta preparada',
        },
        {
          id: 'use',
          number: '04',
          label: 'Usar',
          short: 'Paga, envía, cambia o retira.',
          detail:
            'El dinero vuelve a moverse cuando tú decides. GatoPago presenta la ruta; tu llave autoriza el resultado.',
          status: 'Tú decides el siguiente paso',
        },
      ],
    },
    account: {
      kicker: 'La cuenta',
      greeting: 'Hola, Dani',
      title: 'Una cuenta, no un tablero de blockchain.',
      copy:
        'GatoPago traduce la infraestructura en decisiones cotidianas. El saldo tiene intención; las acciones hablan como tú.',
      concept: 'Concepto visual · datos de ejemplo',
      available: 'Disponible',
      growing: 'Creciendo',
      actions: ['Pagar', 'Enviar', 'Cambiar', 'Escanear'],
      activity: 'Actividad reciente',
      received: 'Pago recibido',
      receivedFrom: 'de @cafe.norte',
      productNotes: [
        'Jerarquía clara antes que densidad',
        'Montos y estados en lenguaje humano',
        'Detalle técnico disponible, nunca impuesto',
      ],
    },
    receive: {
      kicker: 'Cobrar',
      title: 'Cobra sin perseguir el pago.',
      copy:
        'Crea un link o un QR con monto y concepto. Compártelo donde ya conversas; la otra persona abre, revisa y firma el pago.',
      linkLabel: 'Link de cobro',
      amountLabel: 'Total',
      item: '2 cafés + pan de queso',
      status: 'Ejemplo · no cobrable',
      copyLink: 'Copiar ejemplo',
      copied: '¡Ejemplo copiado!',
      note: 'Esta es una demostración visual. El enlace no cobra ni permite enviar fondos.',
      channels: ['WhatsApp', 'QR', 'Mensaje', 'NFC · futuro'],
    },
    grow: {
      kicker: 'Crecer',
      titleLead: 'Una parte lista.',
      titleAccent: 'Otra, creciendo.',
      copy:
        'Separa el dinero que usarás pronto del que quieres poner a trabajar. Sin ocultar protocolo, variabilidad ni riesgo.',
      available: 'Disponible',
      growing: 'Creciendo',
      amount: 'USDC 280.00',
      route: 'Ruta guiada',
      routeValue: 'GatoPago → Aave V3',
      rate: 'Tasa',
      rateValue: 'Variable, no garantizada',
      exit: 'Salida',
      exitValue: 'Solicitada por ti',
      risk: 'Antes de confirmar verás riesgos, costos y condiciones del protocolo.',
      action: 'Ver cómo funciona',
    },
    move: {
      kicker: 'Usar',
      title: 'Mover dinero debería sentirse como elegir un camino.',
      copy:
        'Cuatro verbos reconocibles. Cada ruta termina en una vista previa que puedes entender antes de autorizar.',
      paths: [
        ['Pagar', 'Un link, un QR o una solicitud.', 'P'],
        ['Enviar', 'A un usuario o una dirección compatible.', 'E'],
        ['Cambiar', 'Cotización y costos antes de firmar.', 'C'],
        ['Escanear', 'La cámara encuentra el siguiente paso.', 'Q'],
      ],
      preview: 'Siempre hay vista previa',
    },
    control: {
      kicker: 'Control sin fricción',
      title: 'La experiencia es simple. El control no desaparece.',
      copy:
        'La interfaz reduce ruido, no decisiones. Tu dispositivo guarda la llave de acceso y cada movimiento importante pide confirmación.',
      items: [
        ['Passkey', 'Tu gestor guarda la llave que autoriza movimientos. Entrar con Google o correo no firma pagos ni recupera automáticamente tu cuenta.'],
        ['Recuperación con controles', 'V3 prevé un quorum de recuperación y al menos 72 horas de espera. El correo por sí solo no reemplaza tus llaves.'],
        ['Recibos y rutas', 'Monto, destino, red, costos y estado quedan visibles en el momento adecuado.'],
      ],
      demo: 'Probar diálogo de confirmación',
      demoHint: 'Así se ve una decisión importante en GatoPago.',
    },
    dialog: {
      eyebrow: 'Vista previa',
      title: 'Revisa antes de mover',
      amount: '18.00 USDC',
      rows: [
        ['Destino', '@cafe.norte'],
        ['Concepto', 'Desayuno'],
        ['Red', 'Arbitrum Sepolia'],
        ['Costo estimado', 'Patrocinado en esta alpha'],
      ],
      disclaimer: 'Datos de ejemplo. Nada se enviará desde esta demostración.',
      cancel: 'Volver',
      confirm: 'Entendido',
      close: 'Cerrar diálogo',
    },
    card: {
      kicker: 'Próximo camino',
      title: 'El siguiente paso conecta con el mundo cotidiano.',
      copy:
        'GatoPago Card está en exploración. La diseñamos como una extensión del mismo saldo, pero todavía no prometemos fecha, cobertura ni condiciones.',
      badge: 'Concepto futuro',
      cardLabel: 'GATOPAGO · CONCEPTO',
      cardName: 'DANI',
      waitlist: 'Consultar preguntas frecuentes',
      notice: 'No disponible. Este sitio no registra solicitudes ni reservas.',
    },
    developers: {
      kicker: 'GatoPago para Developers',
      title: 'Dale más vidas a tus pagos.',
      copy:
        'Payment intents, checkout, sandbox y webhooks firmados para pilotos que necesitan mover USDC sin diseñar una wallet desde cero.',
      features: ['Payment intents', 'Idempotencia', 'Webhooks firmados', 'Sandbox de prueba'],
      docs: 'Explorar documentación',
      pilot: 'Conversar sobre un piloto',
      response: 'intent creada',
      note: 'Diseño de la futura API V3. No está publicada ni habilitada para integraciones en este candidato.',
    },
    faq: {
      kicker: 'Preguntas honestas',
      title: 'Lo que conviene saber antes de entrar.',
      items: [
        ['¿GatoPago es un banco?', 'No. GatoPago es una interfaz para una cuenta onchain autocustodiada y programable. La experiencia, riesgos y protecciones no son los de una cuenta bancaria.'],
        ['¿Ya usa dinero real?', 'No. V3 está en desarrollo y pruebas. Este candidato web todavía no crea cuentas ni envía pagos; no envíes fondos reales.'],
        ['¿Quién controla la cuenta?', 'Tú autorizas los movimientos con una llave vinculada a tu dispositivo. GatoPago simplifica la interacción, pero no debería poder mover fondos por sí sola.'],
        ['¿Qué significa “Creciendo”?', 'Es una ruta guiada para depositar USDC en Aave V3. La tasa es variable, el protocolo tiene riesgos y el rendimiento nunca está garantizado.'],
        ['¿GatoPago cobra comisiones?', 'GatoPago muestra 0% de comisión propia entre usuarios en esta etapa. Aun pueden existir costos de red, protocolo, proveedor o conversión.'],
        ['¿La tarjeta ya está disponible?', 'No. GatoPago Card está en exploración. Este sitio no registra interés ni reserva tarjetas.'],
      ],
    },
    final: {
      eyebrow: 'Tu dinero, con siete vidas',
      title: 'Haz que cada pago caiga de pie.',
      copy: 'Ayúdanos a construir una cuenta más clara, útil y bajo tu control. Esta vista previa V3 todavía no mueve fondos.',
      primary: 'Ver estado de la App',
      secondary: 'Volver al ciclo',
    },
    footer: {
      line: 'Tus dólares ya saben moverse. Tu cuenta sigue bajo tu control.',
      product: 'Producto',
      company: 'GatoPago',
      legal: 'Legal',
      links: ['El ciclo', 'La cuenta', 'Crecer', 'Developers'],
      terms: 'Términos',
      privacy: 'Privacidad',
      status: 'Vista previa V3 · no operativa',
      rights: 'GatoPago. Construido con cuidado en Bolivia.',
    },
  },
  en: {
    skip: 'Skip to content',
    nav: {
      aria: 'Main navigation',
      home: 'GatoPago — home',
      cycle: 'The cycle',
      account: 'The account',
      grow: 'Grow',
      card: 'Card',
      developers: 'Developers',
      open: 'Open GatoPago',
      menuOpen: 'Open menu',
      menuClose: 'Close menu',
      language: 'Cambiar a español',
    },
    hero: {
      eyebrow: 'GatoPago · dollars in motion',
      titleLead: 'Your dollars already',
      titleAccent: 'know how to move.',
      copy:
        'Get paid, pay, swap, and grow digital dollars from an account you control. GatoPago handles the path; you authorize every move.',
      primary: 'View App status',
      secondary: 'See how it works',
      alpha: 'V3 preview',
      network: 'Testnet · in development',
      funds: 'Test funds',
      nap: 'Nap mode',
      napOn: 'Nap mode is on',
      napOff: 'We are tracking your money',
      visualLabel: 'GatoPago pixel cat',
      visualNote: 'Your account moves when you give the signal.',
      packet: 'Payment on the move',
    },
    signals: [
      ['You authorize', 'Every movement needs an active key.'],
      ['Identity and signing are separate', 'Google or email to sign in; your keys to authorize.'],
      ['Sponsored gas', 'Planned for testing, subject to availability and limits.'],
      ['Visible risks', 'Routes, costs, and conditions before confirming.'],
    ],
    cycle: {
      kicker: 'A payment’s journey',
      title: 'Your money does not live in a token list.',
      accent: 'It lives in states you understand.',
      intro:
        'Follow one payment through the product. Touch each state to see what changes and what remains under your control.',
      demo: 'Interactive explorer',
      states: [
        { id: 'receive', number: '01', label: 'Receive', short: 'Someone pays your link, QR, or username.', detail: 'The payment reaches your onchain account. You see its source, amount, and network before doing anything else.', status: 'Payment detected' },
        { id: 'available', number: '02', label: 'Available', short: 'Ready to pay, send, or swap.', detail: 'Available is the liquid part of your balance. You do not need to learn contract names to know what you can use now.', status: 'Balance ready' },
        { id: 'growing', number: '03', label: 'Growing', short: 'A portion can enter Aave V3.', detail: 'You choose how much to move. The rate is variable, and the app must show risks, protocol, and exit before confirmation.', status: 'Route prepared' },
        { id: 'use', number: '04', label: 'Use', short: 'Pay, send, swap, or withdraw.', detail: 'The money moves again when you decide. GatoPago presents the route; your key authorizes the outcome.', status: 'You choose the next step' },
      ],
    },
    account: {
      kicker: 'The account',
      greeting: 'Hi, Dani',
      title: 'An account, not a blockchain dashboard.',
      copy: 'GatoPago translates infrastructure into everyday decisions. The balance has intent; actions speak like you do.',
      concept: 'Visual concept · example data',
      available: 'Available',
      growing: 'Growing',
      actions: ['Pay', 'Send', 'Swap', 'Scan'],
      activity: 'Recent activity',
      received: 'Payment received',
      receivedFrom: 'from @cafe.norte',
      productNotes: ['Clear hierarchy over density', 'Amounts and states in human language', 'Technical detail available, never imposed'],
    },
    receive: {
      kicker: 'Get paid',
      title: 'Get paid without chasing the payment.',
      copy: 'Create a link or QR with an amount and note. Share it where you already talk; the other person opens, reviews, and signs the payment.',
      linkLabel: 'Payment link',
      amountLabel: 'Total',
      item: '2 coffees + cheese bread',
      status: 'Example · not payable',
      copyLink: 'Copy example',
      copied: 'Example copied!',
      note: 'This is a visual demonstration. The link does not collect payments or allow funds to be sent.',
      channels: ['WhatsApp', 'QR', 'Message', 'NFC · future'],
    },
    grow: {
      kicker: 'Grow',
      titleLead: 'One part ready.',
      titleAccent: 'Another, growing.',
      copy: 'Separate the money you will use soon from what you want to put to work. Without hiding protocol, variability, or risk.',
      available: 'Available',
      growing: 'Growing',
      amount: 'USDC 280.00',
      route: 'Guided route',
      routeValue: 'GatoPago → Aave V3',
      rate: 'Rate',
      rateValue: 'Variable, not guaranteed',
      exit: 'Exit',
      exitValue: 'Requested by you',
      risk: 'Before confirming, you will see protocol risks, costs, and conditions.',
      action: 'See how it works',
    },
    move: {
      kicker: 'Use',
      title: 'Moving money should feel like choosing a path.',
      copy: 'Four recognizable verbs. Every path ends in a preview you can understand before authorizing.',
      paths: [['Pay', 'A link, QR, or request.', 'P'], ['Send', 'To a user or compatible address.', 'S'], ['Swap', 'Quote and costs before signing.', 'W'], ['Scan', 'The camera finds the next step.', 'Q']],
      preview: 'There is always a preview',
    },
    control: {
      kicker: 'Control without friction',
      title: 'The experience is simple. Control does not disappear.',
      copy: 'The interface reduces noise, not decisions. Your device holds the access key, and every important movement asks for confirmation.',
      items: [['Passkey', 'Your credential manager stores the key that authorizes movements. Google or email sign-in does not sign payments or automatically recover your account.'], ['Recovery with controls', 'V3 specifies a recovery quorum and at least a 72-hour wait. Email alone cannot replace your keys.'], ['Receipts and routes', 'Amount, destination, network, costs, and status become visible at the right moment.']],
      demo: 'Try the confirmation dialog',
      demoHint: 'This is how an important decision looks in GatoPago.',
    },
    dialog: {
      eyebrow: 'Preview', title: 'Review before moving', amount: '18.00 USDC',
      rows: [['Destination', '@cafe.norte'], ['Note', 'Breakfast'], ['Network', 'Arbitrum Sepolia'], ['Estimated cost', 'Sponsored in this alpha']],
      disclaimer: 'Example data. Nothing will be sent from this demo.', cancel: 'Go back', confirm: 'Got it', close: 'Close dialog',
    },
    card: {
      kicker: 'Next path', title: 'The next step connects to everyday life.',
      copy: 'GatoPago Card is being explored. We are designing it as an extension of the same balance, but we are not promising a date, coverage, or terms yet.',
      badge: 'Future concept', cardLabel: 'GATOPAGO · CONCEPT', cardName: 'DANI', waitlist: 'Read the FAQ', notice: 'Not available. This site does not record requests or reservations.',
    },
    developers: {
      kicker: 'GatoPago for Developers', title: 'Give your payments more lives.',
      copy: 'Payment intents, checkout, sandbox, and signed webhooks for pilots that need to move USDC without designing a wallet from scratch.',
      features: ['Payment intents', 'Idempotency', 'Signed webhooks', 'Test sandbox'], docs: 'Explore documentation', pilot: 'Talk about a pilot', response: 'intent created',
      note: 'Future V3 API design. Not published or enabled for integrations in this candidate.',
    },
    faq: {
      kicker: 'Honest questions', title: 'What you should know before entering.',
      items: [
        ['Is GatoPago a bank?', 'No. GatoPago is an interface for a self-custodial, programmable onchain account. Its experience, risks, and protections are not those of a bank account.'],
        ['Does it use real money yet?', 'No. V3 is in development and testing. This web candidate cannot create accounts or send payments. Do not send real funds.'],
        ['Who controls the account?', 'You authorize movements with your keys. Google or email sign-in alone does not authorize payments.'],
        ['What does “Growing” mean?', 'This visual concept shows a future guided route to Aave V3. It is not enabled in this candidate; yield would be variable and never guaranteed.'],
        ['Does GatoPago charge fees?', 'The commercial goal is no GatoPago fee. Network, protocol, provider, or conversion costs may still apply and must be shown before confirmation.'],
        ['Is the card available?', 'No. GatoPago Card is being explored. This site does not record interest or reserve cards.'],
      ],
    },
    final: {
      eyebrow: 'Your money, with nine lives', title: 'Make every payment land on its feet.',
      copy: 'Help us build an account that is clearer, more useful, and under your control. This V3 preview cannot move funds.', primary: 'View App status', secondary: 'Back to the cycle',
    },
    footer: {
      line: 'Your dollars already know how to move. Your account stays under your control.', product: 'Product', company: 'GatoPago', legal: 'Legal',
      links: ['The cycle', 'The account', 'Grow', 'Developers'], terms: 'Terms', privacy: 'Privacy', status: 'V3 preview · not operational', rights: 'GatoPago. Built with care in Bolivia.',
    },
  },
} as const;
